export const COMPONENT_NAME = "{{ .Any.COMPONENT_NAME }}"
export const NEXUS_NAME = "{{ .Any.NEXUS_NAME }}"
export const NEXUS_URL = "{{ .Any.NEXUS_URL }}"
export const DEV_PORTAL_URL = "{{ .Any.DEV_PORTAL_URL }}"
export const FAVICON_URL = "{{ .Any.FAVICON_URL }}"
